// An example of nested try statements.
class _7NestTry {
    public static void main(String[] args) {
        try {
            int a = args.length;
            /* If no command line args are present,
               the following statements will generate devide-by-zero exception.
             */
            int b = 42 / a;

            System.out.println("a: " + a);

            try { // nested try block
                /* if one command-line arg used,
                   then a devide-by-zero exception will be generated by 
                   the following code.
                 */
                if(a == 1) a = a/(a - a); // devision by zero .

                /* If two command-line args are used, then 
                 * generate a out-of-bounds exception.
                 */
                if(a == 2) {
                    int c[] = {1};
                    c[42] = 99; // generate an out-of-bounds exception.
                }
            } catch (ArrayIndexOutOfBoundsException e) {
                System.out.println("Array out-of-bounds : " + e);
            }
        } catch (ArithmeticException e) {
            System.out.println("Devide by 0: " + e);
        }
    }
}
